#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the embedded default NNUE C++ source.")
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--symbol", default="EMBEDDED_DEFAULT_NET")
    parser.add_argument("--name", default=None)
    args = parser.parse_args()

    data = args.input.read_bytes()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    name = args.name or args.input.name

    with args.output.open("w", encoding="utf-8", newline="\n") as out:
        out.write("// Generated by scripts/embed_nnue.py. Do not edit by hand.\n")
        out.write("#include <cstddef>\n")
        out.write("#include <cstdint>\n\n")
        out.write("namespace SHAYVERI::NNUE {\n\n")
        out.write(f'extern const char EMBEDDED_DEFAULT_NET_NAME[] = "{name}";\n')
        out.write(f"extern const std::size_t {args.symbol}_SIZE = {len(data)};\n")
        out.write(f"extern const std::uint8_t {args.symbol}[] = {{\n")
        for i in range(0, len(data), 12):
            chunk = data[i:i + 12]
            out.write("    ")
            out.write(", ".join(f"0x{b:02x}" for b in chunk))
            out.write(",\n")
        out.write("};\n\n")
        out.write("} // namespace SHAYVERI::NNUE\n")


if __name__ == "__main__":
    main()
