#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

namespace {

std::vector<std::uint8_t> read_file(const std::filesystem::path &path) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        throw std::runtime_error("cannot open input: " + path.string());
    }

    in.seekg(0, std::ios::end);
    const std::streamoff size = in.tellg();
    if (size <= 0) {
        throw std::runtime_error("empty or unreadable input: " + path.string());
    }
    in.seekg(0, std::ios::beg);

    std::vector<std::uint8_t> data(static_cast<std::size_t>(size));
    if (!in.read(reinterpret_cast<char *>(data.data()), static_cast<std::streamsize>(size))) {
        throw std::runtime_error("failed to read input: " + path.string());
    }
    return data;
}

std::string escaped_cpp_string(const std::string &value) {
    std::string out;
    out.reserve(value.size());
    for (unsigned char c : value) {
        switch (c) {
        case '\\':
            out += "\\\\";
            break;
        case '"':
            out += "\\\"";
            break;
        case '\n':
            out += "\\n";
            break;
        case '\r':
            out += "\\r";
            break;
        case '\t':
            out += "\\t";
            break;
        default:
            if (c < 32 || c > 126) {
                static constexpr char HEX[] = "0123456789abcdef";
                out += "\\x";
                out += HEX[(c >> 4) & 0xF];
                out += HEX[c & 0xF];
            } else {
                out += static_cast<char>(c);
            }
            break;
        }
    }
    return out;
}

void usage(const char *argv0) {
    std::cerr << "usage: " << argv0 << " <input.nnue> <output.cpp> [name]\n";
}

} // namespace

int main(int argc, char **argv) {
    if (argc < 3 || argc > 4) {
        usage(argv[0]);
        return 1;
    }

    try {
        const std::filesystem::path input = argv[1];
        const std::filesystem::path output = argv[2];
        const std::string net_name = argc == 4 ? argv[3] : input.filename().string();
        const std::vector<std::uint8_t> data = read_file(input);

        if (output.has_parent_path()) {
            std::filesystem::create_directories(output.parent_path());
        }

        std::ofstream out(output, std::ios::binary);
        if (!out) {
            throw std::runtime_error("cannot open output: " + output.string());
        }

        out << "// Generated by src/tools/embed_nnue.cpp. Do not edit by hand.\n";
        out << "#include <cstddef>\n";
        out << "#include <cstdint>\n\n";
        out << "namespace SHAYVERI::NNUE {\n\n";
        out << "extern const char EMBEDDED_DEFAULT_NET_NAME[] = \""
            << escaped_cpp_string(net_name) << "\";\n";
        out << "extern const std::size_t EMBEDDED_DEFAULT_NET_SIZE = "
            << data.size() << ";\n";
        out << "extern const std::uint8_t EMBEDDED_DEFAULT_NET[] = {\n";

        out << std::hex << std::setfill('0');
        for (std::size_t i = 0; i < data.size(); i += 12) {
            out << "    ";
            const std::size_t end = std::min<std::size_t>(i + 12, data.size());
            for (std::size_t j = i; j < end; ++j) {
                if (j != i) {
                    out << ", ";
                }
                out << "0x" << std::setw(2) << static_cast<unsigned>(data[j]);
            }
            out << ",\n";
        }

        out << "};\n\n";
        out << "} // namespace SHAYVERI::NNUE\n";
    } catch (const std::exception &e) {
        std::cerr << "embed_nnue: " << e.what() << '\n';
        return 1;
    }

    return 0;
}
